# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/github_private_strategy.rb"
class Fittools < Formula
  desc "CLI tools for working with FIT files"
  homepage "https://github.com/jacobfg/fittools-golang"
  version "0.0.2"
  license "Apache-2.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jacobfg/fittools-golang/releases/download/0.0.2/fittools_0.0.2_darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fc477ea27b24bc21cfbfc0ef612ad265543f9ff1280cac8bcf2db8284974e0d7"

      def install
        bin.install "fittools"
        bash_completion.install "completions/fittools.bash"
        fish_completion.install "completions/fittools.fish"
        zsh_completion.install "completions/fittools.zsh" => "_fittools"

        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jacobfg/fittools-golang/releases/download/0.0.2/fittools_0.0.2_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0d7792adc7f423cac03dc359e2352d3c8f7886d517ef8f69f43ca04b66696bd5"

      def install
        bin.install "fittools"
        bash_completion.install "completions/fittools.bash"
        fish_completion.install "completions/fittools.fish"
        zsh_completion.install "completions/fittools.zsh" => "_fittools"

        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/fittools version"
    # test version to ensure that version number is embedded in binary
    # somehow add os/arch in version output
    assert_match "fittools: 0.0.2 (a33ccf8)", shell_output("#{bin}/fittools version")
    # assert_match "built by #{tap.user}", shell_output("#{bin}/fittools version")
  end
end
