# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/github_private_strategy.rb"
class JacobfgTools < Formula
  desc "Tools written in GoLang"
  homepage "https://jacobfg/jacobfg-tools"
  version "0.0.0"
  license "Apache-2.0"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jacobfg/jacobfg-tools/releases/download/0.0.0/jacobfg-tools_0.0.0_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ff45c27095423961e786cf969c05483e754e872f2d36315b6b64ea7f12bcb1ba"
    end
    if Hardware::CPU.arm?
      url "https://github.com/jacobfg/jacobfg-tools/releases/download/0.0.0/jacobfg-tools_0.0.0_darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "064f80eef98d1fbf70be9a3c39d9c44e1e7d0471e4c9b73ea11ab98a30ac1eee"
    end
  end

  def install
    bin.install "jacobfg-tools"
  end

  test do
    system "#{bin}/helloworld version"
  end
end
