# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/github_private_strategy.rb"
class JacobfgTools < Formula
  desc "Tools written in GoLang"
  homepage "https://jacobfg/jacobfg-tools"
  version "0.0.0"
  license "Apache-2.0"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jacobfg/jacobfg-tools/releases/download/0.0.0/jacobfg-tools_0.0.0_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "29cf48bd83a10473c486928c539a2b7d2dc6a9306bd54c8a787356d3b6232962"
    end
    if Hardware::CPU.arm?
      url "https://github.com/jacobfg/jacobfg-tools/releases/download/0.0.0/jacobfg-tools_0.0.0_darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a2a2d76ae2255a366e5027ff93f2cede61e3fdae2f92945ee44b3ee2dd36b275"
    end
  end

  def install
    bin.install "helloworld"
  end

  test do
    system "#{bin}/helloworld version"
  end
end
